version: '3'
services:
    mongo:
        ports: 
            - "27017:27017"
        volumes: 
            - /var/lib/docker/volumes/mongoData/_data:/data/db
        image: mongo
    # postgres:
    #     ports:
    #         - "54320:54320"
    #     volumes:
    #         - /var/lib/postgresql/data
    #     image: postgres:11
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        environment: 
            DB_HOST: mongo