version: '3'
services:
    mongo:
        ports: 
            - "27017:27017"
        volumes: 
            - mongoData:/data/db
        image: mongo
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        environment: 
            DB_HOST: mongo
        image: samgcode/skills-comp_backend:1.0
    frontend:
        build: ./frontend
        ports:
            - "8080:80"
        environment: 
            HOST_NAME: backend
        image: samgcode/skills-comp_frontend:1.0

volumes: 
    mongoData: