INSERT INTO items (name, description, imagename)
VALUES (
    'Bio degradable spoons pack',
    'A pack of ten spoons, that are all high quality and energy efficient.',
    'manySpoons'
), (
    'Colored spoons pack',
    'A packadge containing ten bio degradable spoons of all different colors.',
    'rainbowSpoons'
), (
    'Single spoon',
    'Uno spoon',
    'SPOON'
), (
    'Colored spoon',
    'A packadge containing one bio degradable spoon of any different color.',
    'rainbowSpoons'
);

INSERT INTO reviews (username, review, rating, item)
VALUES (
	'Jeff',
	'I love the colors of these spoons, they work very well would buy again.',
	4,
    2
), (
	'Stev',
	'Very good spoons, very bio-degradable would, very good curve yes yes very good.',
	5,
    1
), (
	'Steve',
	'Definately good spoon would spoon again.',
	4,
    3
), (
	'Kevin',
	'This is a very good colorfull spoon I love I gave them to my kids, and my parents, and my friends, they are just the best spoons ever.',
	5,
    4
);
