INSERT INTO reviews (username, review, rating, item)
VALUES (
	'Jeff',
	'This is a review by a person that has a rating and this is a very good company yes yes.',
	4,
    2
),
(
	'Stev',
	'Yes yes very good, very cool yes good would spoon again',
	5,
    1
);

INSERT INTO items (name, description, imagename)
VALUES (
    'Bio degradable spoons pack',
    'A pack of ten spoons, that are all high quality and energy efficient.',
    'manySpoons'
), (
    'Colored spoons pack',
    'A packadge containing ten bio degradable spoons of all different colors.',
    'rainbowSpoons'
), (
    'Single spoon',
    'Uno spoon',
    'SPOON'
), (
    'Colored spoon',
    'A packadge containing one bio degradable spoon of any different color.',
    'rainbowSpoons'
);
